
##########################################################################################################################

- Media Management:
  - Radarr:
      icon: radarr.png
      href: http://192.168.30.5:7878
      description: Movie Manager
      server: my-docker
      container: radarr
      widget:
        type: radarr
        url: http://192.168.30.5:7878
        key: ${RADARR_KEY}
        fields: ["wanted", "missing", "queued", "movies"]

  - Prowlarr:
      icon: prowlarr.png
      href: http://192.168.30.5:9696
      container: prowlarr
      description: Indexer integration for downloads
      widget:
          type: prowlarr
          url: http://192.168.30.5:9696
          key: ${PROWLARR_KEY}
          fields: ["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs", "numberOfFailQueries"]

################################################################################       
- Utilities:
  - Speedtest:
        icon: speedtest-tracker.png
        href: http://192.168.30.5:8081
        description: Network speed tracker
        container: speedtest
        widget:
          type: speedtest-tracker
          url: http://192.168.30.5:8081
          bitratePrecision: 0
          fields: ["download", "upload", "ping"]

  - Adguard:
      icon: adguard-home.png
      href: http://192.168.30.5
      description: DNS Filter
      container: adguard
      widget:
        type: adguard
        url: http://192.168.30.5
        username: ${USER}
        password: ${PASS}
        fields: ["queries", "blocked", "latency"]


           
##########################################################################################################################

- Media Players:
  - Jellyfin:  
      icon: jellyfin.png
      hreff: http://192.168.30.5:8096
      container: jellyfin
      description: Media Player
      widget:
          type: jellyfin
          url: http://192.168.30.5:8096
          key: ${JELLYFIN_PASS}
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          enableMediaControl: false # optional, defaults to true
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true        
          
  - Plex:
      icon: plex.png
      hreff: http://192.168.30.5:32400
      container: plex
      description: Family Server        
      widget:
          type: plex
          url: http://192.168.30.5:32400
          key: ${PLEX_KEY} # see https://www.plexopedia.com/plex-media-server/general/plex-token/
##########################################################################################################################

- File Management:
  - qBittorrent:
        icon: qbittorrent.png
        hreff: http://192.168.30.5:8080
        description: Torrent Client
        container: qbittorrent
        widget:
          type: qbittorrent
          url: http://192.168.30.5:8080
          username: ${USER}
          password: ${PASS}
          enableLeechProgress: true # optional, defaults to false
          fields: ['download', 'seed', 'upload']

##########################################################################################################################

- NocturnOwl:
  - Jellyfin:  
      icon: jellyfin.png
      href: http://192.168.30.5:8096
      target: _blank
       
  - Plex:
      icon: plex.png
      href: http://192.168.30.5:32400    
      target: _blank

  - Radarr:
      icon: radarr.png
      href: http://192.168.30.5:7878
      target: _blank  

  - Prowlarr:
      icon: prowlarr.png
      href: http://192.168.30.5:9696
      target: _blank  

  - qBittorrent:
      icon: qbittorrent.png
      href: http://192.168.30.5:8080
      target: _blank  

  - PrivateHD:
      icon: /icons/hd.png
      href: https://privatehd.to/
      target: _blank  

##########################################################################################################################

- Technical:

  - Adguard Home:
      icon: adguard-home.png
      href: http://192.168.30.5
      target: _blank

  - Github - NocturnOwl:
      icon: github.png
      href: https://github.com/egomez174/Homelab
      target: _blank

  - HomePage Docs:
      icon: homepage.png
      href: https://gethomepage.dev/
      target: _blank

  - Portainer:
       icon: portainer.png
       href: https://192.168.30.5:9443/#!/home
       target: _blank

##########################################################################################################################

- WGU:

  - WGU Homepage:
      icon: /icons/wgu.png
      href: https://my.wgu.edu/home
      target: _blank

  - Try Hack Me:
      icon: /icons/thm.png
      href: https://tryhackme.com/dashboard
      target: _blank

  - Udemy:
      icon: udemy.png
      href: https://wgu.udemy.com/
      target: _blank



##########################################################################################################################





##########################################################################################################################
